config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :ubications
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_one :ubication
	accepts_nested_attributes_for :ubication, allow_destroy: true
  
  	validates :nombre, presence: { message: ": es un campo obligatorio"}

end

app/models/ubication.rb
class Ubication < ActiveRecord::Base
	belongs_to :Place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @ubication = @place.build_ubication
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:nombre, :descripcion, ubication_attributes: [ :id, :latitud, :longitud, :_destroy ])
    end
end

app/controllers/ubications_controller.rb
class UbicationsController < ApplicationController
  before_action :set_ubication, only: [:show, :edit, :update, :destroy]

  # GET /ubications
  # GET /ubications.json
  def index
    @ubications = Ubication.all
  end

  # GET /ubications/1
  # GET /ubications/1.json
  def show
  end

  # GET /ubications/new
  def new
    @ubication = Ubication.new
  end

  # GET /ubications/1/edit
  def edit
  end

  # POST /ubications
  # POST /ubications.json
  def create
    @ubication = Ubication.new(ubication_params)

    respond_to do |format|
      if @ubication.save
        format.html { redirect_to @ubication, notice: 'Ubication was successfully created.' }
        format.json { render :show, status: :created, location: @ubication }
      else
        format.html { render :new }
        format.json { render json: @ubication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ubications/1
  # PATCH/PUT /ubications/1.json
  def update
    respond_to do |format|
      if @ubication.update(ubication_params)
        format.html { redirect_to @ubication, notice: 'Ubication was successfully updated.' }
        format.json { render :show, status: :ok, location: @ubication }
      else
        format.html { render :edit }
        format.json { render json: @ubication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ubications/1
  # DELETE /ubications/1.json
  def destroy
    @ubication.destroy
    respond_to do |format|
      format.html { redirect_to ubications_url, notice: 'Ubication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ubication
      @ubication = Ubication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ubication_params
      params.require(:ubication).permit(:latitud, :longitud)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/ubications_helper.rb
module UbicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ubicacion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.12/gmaps.min.js"></script>
</body>
</html>

app/views/places/_form.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <fieldset>
    <h4>Ubicación</h4>
    <%= f.fields_for :ubication do |ubication_fields|%>
      <div class="field">
        <%= ubication_fields.label :latitud %>
        <%= ubication_fields.text_field :latitud %>
      </div>
      <div class="field">
        <%= ubication_fields.label :longitud %>
        <%= ubication_fields.text_field :longitud %>
      </div>
      <div class="field">
        <%= ubication_fields.check_box :_destroy %>
        <%= ubication_fields.label :_destroy, 'remove' %>
      </div>  
       <a class="" onclick="geolocalizar()">
        --> Mi Ubicación <--
       </a>    
    <% end %>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_script.html.erb
<script type="text/javascript">
    var map;
    $(document).ready(function(){
      map = new GMaps({
        el: '#map',
        lat: $("#latitud").val(),
        lng: $("#longitud").val()
      });
      /*
      map.addMarker({
        lat: -12.043333,
        lng: -77.03,
        title: 'Lima',
        details: {
          database_id: 42,
          author: 'HPNeo'
        },
        click: function(e){
          if(console.log)
            console.log(e);
          alert('You clicked in this marker');
        },
        mouseover: function(e){
          if(console.log)
            console.log(e);
        }
      });*/
      map.addMarker({
        lat: $("#latitud").val(),
        lng: $("#longitud").val(),
        title: 'Marker with InfoWindow',
        infoWindow: {
          content: '<h3>Etiqueta html</h3>'
        }
      });
    });
</script>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.nombre %></td>
        <td><%= place.descripcion %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&language=es&region=MX&signed_in=true"></script>
<p id="notice"><%= notice %></p>
<p>
  <strong>Nombre:</strong>
  <%= @place.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @place.descripcion %>
</p>

<h4>Ubicación</h4>
<p>
	<strong id="latitud_label">Latitud:</strong>
	<%= @place.ubication.latitud %>
	<%= hidden_field_tag(:latitud, @place.ubication.latitud) %>
</p>
<p>
	<strong id="longitud_label">Longitud:</strong>
	<%= @place.ubication.longitud %>
	<%= hidden_field_tag(:longitud, @place.ubication.longitud) %>
</p>
<div class="contenedor">
	<div id="map"></div>
</div>
<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>
<%= render "script" %>

app/views/ubications/_form.html.erb
<%= form_for(@ubication) do |f| %>
  <% if @ubication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ubication.errors.count, "error") %> prohibited this ubication from being saved:</h2>

      <ul>
      <% @ubication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitud %><br>
    <%= f.text_field :latitud %>
  </div>
  <div class="field">
    <%= f.label :longitud %><br>
    <%= f.text_field :longitud %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ubications/edit.html.erb
<h1>Editing Ubication</h1>

<%= render 'form' %>

<%= link_to 'Show', @ubication %> |
<%= link_to 'Back', ubications_path %>

app/views/ubications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ubications</h1>

<table>
  <thead>
    <tr>
      <th>Latitud</th>
      <th>Longitud</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ubications.each do |ubication| %>
      <tr>
        <td><%= ubication.latitud %></td>
        <td><%= ubication.longitud %></td>
        <td><%= link_to 'Show', ubication %></td>
        <td><%= link_to 'Edit', edit_ubication_path(ubication) %></td>
        <td><%= link_to 'Destroy', ubication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ubication', new_ubication_path %>

app/views/ubications/new.html.erb
<h1>New Ubication</h1>

<%= render 'form' %>

<%= link_to 'Back', ubications_path %>

app/views/ubications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitud:</strong>
  <%= @ubication.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @ubication.longitud %>
</p>

<%= link_to 'Edit', edit_ubication_path(@ubication) %> |
<%= link_to 'Back', ubications_path %>